import React, { useState, useEffect } from 'react';
import { X, Sparkles, Bot, CheckCircle2, ArrowRight, ArrowLeft, Loader2, AlertCircle, Briefcase } from 'lucide-react';
import { supabase } from '../supabaseClient'; // 🚀 ADDED: Required to get the auth token!

interface CreateJobModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function CreateJobModal({ isOpen, onClose }: CreateJobModalProps) {
  // Form State
  const [title, setTitle] = useState("Senior CNC Machinist");
  const [department, setDepartment] = useState("Production");
  const [location, setLocation] = useState("Detroit, MI - On-site");
  const [type, setType] = useState("Full-time");
  const [salaryMin, setSalaryMin] = useState(""); 
  const [salaryMax, setSalaryMax] = useState(""); 
  
  // Content State
  const [description, setDescription] = useState("");
  const [responsibilities, setResponsibilities] = useState("");
  const [skills, setSkills] = useState("");
  
  // UI & Validation State
  const [isGenerating, setIsGenerating] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [activeStep, setActiveStep] = useState(1);
  const [formError, setFormError] = useState(""); 

  useEffect(() => {
    if (isOpen) {
      setTitle("Senior CNC Machinist");
      setDepartment("Production");
      setLocation("Detroit, MI - On-site");
      setType("Full-time");
      setSalaryMin("");
      setSalaryMax("");
      setDescription("");
      setResponsibilities("");
      setSkills("");
      setActiveStep(1);
      setFormError("");
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleNextStep = () => {
    setFormError(""); 
    
    // Step 1 Validation
    if (activeStep === 1) {
      if (!title.trim() || !department.trim() || !location.trim() || !type.trim() || !salaryMin.toString().trim() || !salaryMax.toString().trim()) {
        setFormError("All basic details, including Salary Range, are required.");
        return;
      }
      if (Number(salaryMin) > Number(salaryMax)) {
        setFormError("Minimum salary cannot be greater than maximum salary.");
        return;
      }
    }
    
    // Step 2 Validation
    if (activeStep === 2) {
      if (!description.trim() || !responsibilities.trim() || !skills.trim()) {
        setFormError("All job requirements must be filled out or generated by AI.");
        return;
      }
    }

    setActiveStep(prev => Math.min(3, prev + 1));
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    setFormError(""); 

    try {
      const systemPrompt = `You are an expert HR Technical Recruiter writing a job requisition. 
      Create a highly professional and realistic job profile based on these details:
      - Job Title: ${title}
      - Department: ${department}
      - Location: ${location}
      - Employment Type: ${type}
      
      You must respond EXACTLY in this JSON format. Do not include markdown formatting or extra text.
      {
        "description": "Write a 2-3 paragraph engaging overview of the role and the team.",
        "responsibilities": "• First bullet point\\n• Second bullet point\\n• Third bullet point",
        "skills": "• First required skill\\n• Second required skill\\n• Third required skill"
      }`;

      // Routing through OpenRouter API
      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_OPENROUTER_API_KEY}`,
          'HTTP-Referer': window.location.origin, 
          'X-Title': 'Talent Scout ATS'           
        },
        body: JSON.stringify({
          model: "google/gemini-1.5-flash", 
          messages: [{ role: "user", content: systemPrompt }],
          response_format: { type: "json_object" }, 
          temperature: 0.7
        })
      });

      if (!response.ok) throw new Error("Failed to communicate with the AI model.");

      const data = await response.json();
      const generatedContent = JSON.parse(data.choices[0].message.content);

      setDescription(generatedContent.description || "");
      setResponsibilities(generatedContent.responsibilities || "");
      setSkills(generatedContent.skills || "");
      
      setActiveStep(3); 

    } catch (error) {
      console.error("AI Generation Error:", error);
      setFormError("AI generation failed. Please check your OpenRouter API key in the .env file.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePublishJob = async () => {
    setFormError("");
    
    if (!description.trim() || !responsibilities.trim() || !skills.trim()) {
      setFormError("Cannot publish: Job requirements are incomplete.");
      return;
    }

    setIsPublishing(true);
    try {
      // 🚀 CRITICAL FIX: Grab the active session token before fetching
      const { data: { session } } = await supabase.auth.getSession();

      if (!session) {
        throw new Error("No active authentication session found.");
      }

      const response = await fetch('http://localhost:8000/api/jobs', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}` // 🚀 Pass the VIP pass to Python!
        },
        body: JSON.stringify({
          title, 
          department, 
          location, 
          employment_type: type,
          salary_min: Number(salaryMin), 
          salary_max: Number(salaryMax),
          description, 
          responsibilities, 
          skills
        })
      });

      if (!response.ok) {
        throw new Error(`Failed to save job on the server. Status: ${response.status}`);
      }

      setActiveStep(4);
      window.dispatchEvent(new Event('job-created'));

    } catch (error) {
      console.error("Save error:", error);
      setFormError("There was an error saving the job. Ensure your Python backend is running.");
    } finally {
      setIsPublishing(false);
    }
  };

  const steps = ["Details", "Requirements", "AI Optimization"];

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4"
      onMouseDown={onClose} 
    >
      <div 
        className="bg-white rounded-xl shadow-2xl w-full max-w-6xl h-[85vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200"
        onMouseDown={(e) => e.stopPropagation()} 
      >
        
        {/* Header / Stepper (Hidden on Success Step) */}
        {activeStep < 4 && (
          <div className="flex justify-between items-center px-8 py-4 border-b border-slate-200 bg-white z-10">
            <div className="flex-1 flex justify-center items-center gap-0 relative">
               {steps.map((step, index) => {
                 const stepNumber = index + 1;
                 const isActive = stepNumber === activeStep;
                 const isPassed = stepNumber < activeStep;
                 return (
                   <React.Fragment key={step}>
                     <div className="flex flex-col items-center z-10 bg-white px-4">
                       <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold border-2 transition-colors
                         ${isActive ? 'border-blue-600 text-blue-600 bg-blue-50' : 
                           isPassed ? 'border-blue-600 bg-blue-600 text-white' : 
                           'border-slate-300 text-slate-400 bg-white'}`}>
                         {isPassed ? <CheckCircle2 size={16} /> : stepNumber}
                       </div>
                       <span className={`text-xs mt-2 font-bold ${isActive || isPassed ? 'text-blue-700' : 'text-slate-400'}`}>
                         {step}
                       </span>
                     </div>
                     {index < steps.length - 1 && (
                       <div className={`flex-1 h-0.5 max-w-[100px] transition-colors ${isPassed ? 'bg-blue-600' : 'bg-slate-200'}`} />
                     )}
                   </React.Fragment>
                 )
               })}
            </div>
            <button onClick={onClose} className="p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700 rounded-lg absolute right-6">
              <X size={20} />
            </button>
          </div>
        )}

        {/* CONDITIONAL RENDER: SUCCESS SCREEN OR FORM */}
        {activeStep === 4 ? (
          <div className="flex-1 flex flex-col items-center justify-center bg-[#f8fafc] p-8 text-center animate-in zoom-in duration-500">
            <div className="w-24 h-24 bg-green-100 rounded-full flex items-center justify-center mb-6 shadow-inner">
              <CheckCircle2 size={48} className="text-green-600" />
            </div>
            <h2 className="text-3xl font-bold text-slate-900 mb-3">Requisition Published!</h2>
            <p className="text-slate-500 max-w-md mx-auto mb-10 text-lg leading-relaxed">
              The AI Job Architect has successfully generated and deployed the <strong className="text-slate-800">{title}</strong> requisition to your database.
            </p>
            <button 
              onClick={onClose}
              className="px-8 py-4 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-xl shadow-lg flex items-center gap-3 transition-transform hover:scale-105 active:scale-95"
            >
              <Briefcase size={20} /> Go to Job Page
            </button>
          </div>
        ) : (
          /* STANDARD SPLIT MODAL BODY (Steps 1-3) */
          <div className="flex flex-1 overflow-hidden bg-[#f8fafc]">
            
            {/* Left Column: Form Inputs */}
            <div className="flex-[2] flex flex-col bg-white border-r border-slate-200 relative overflow-hidden">
              
              <div className="flex-1 overflow-y-auto p-8 pb-32">
                <h2 className="text-xl font-bold text-slate-900 mb-6">
                  {activeStep === 1 ? "Basic Requisition Details" : activeStep === 2 ? "Job Requirements" : "Review Profile"}
                </h2>
                
                {formError && (
                  <div className="mb-6 p-4 bg-red-50 text-red-700 text-sm font-bold rounded-lg border border-red-200 flex items-center gap-2 animate-in slide-in-from-top-2">
                    <AlertCircle size={18} />
                    {formError}
                  </div>
                )}

                {/* STEP 1 CONTENT */}
                {activeStep === 1 && (
                  <div className="grid grid-cols-2 gap-6 animate-in fade-in slide-in-from-left-4">
                    <div className="col-span-2">
                      <label className="block text-xs font-bold text-slate-600 mb-2 uppercase">Job Title</label>
                      <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
                    </div>
                    
                    <div>
                      <label className="block text-xs font-bold text-slate-600 mb-2 uppercase">Department</label>
                      <input 
                        type="text" 
                        value={department} 
                        onChange={(e) => setDepartment(e.target.value)} 
                        placeholder="e.g. Engineering, Sales, etc." 
                        className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white" 
                      />
                    </div>
                    
                    <div>
                      <label className="block text-xs font-bold text-slate-600 mb-2 uppercase">Location</label>
                      <input type="text" value={location} onChange={(e) => setLocation(e.target.value)} className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
                    </div>

                    <div className="col-span-2">
                      <label className="block text-xs font-bold text-slate-600 mb-2 uppercase">Employment Type</label>
                      <select 
                        value={type} 
                        onChange={(e) => setType(e.target.value)} 
                        className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none bg-white"
                      >
                        <option value="Full-time">Full-time</option>
                        <option value="Part-time">Part-time</option>
                        <option value="Contract">Contract</option>
                        <option value="Internship">Internship</option>
                      </select>
                    </div>
                    
                    <div className="col-span-2">
                      <label className="block text-xs font-bold text-slate-600 mb-2 uppercase">Salary Range (INR)</label>
                      <div className="flex items-center gap-3">
                        <div className="flex-1 relative">
                          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-medium">₹</span>
                          <input type="number" placeholder="Minimum" value={salaryMin} onChange={(e) => setSalaryMin(e.target.value)} className="w-full pl-8 pr-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
                        </div>
                        <span className="text-slate-400 font-bold">-</span>
                        <div className="flex-1 relative">
                          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-medium">₹</span>
                          <input type="number" placeholder="Maximum" value={salaryMax} onChange={(e) => setSalaryMax(e.target.value)} className="w-full pl-8 pr-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {/* STEP 2 & 3 CONTENT */}
                {activeStep >= 2 && (
                  <div className="space-y-6 animate-in fade-in slide-in-from-right-4">
                    <div>
                      <label className="block text-sm font-bold text-slate-700 mb-2">Job Description</label>
                      <textarea rows={4} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Generate description with AI..." className="w-full px-4 py-3 border rounded-lg outline-none resize-none" />
                    </div>
                    <div>
                      <label className="block text-sm font-bold text-slate-700 mb-2">Key Responsibilities</label>
                      <textarea rows={4} value={responsibilities} onChange={(e) => setResponsibilities(e.target.value)} placeholder="Awaiting AI generation..." className="w-full px-4 py-3 border rounded-lg outline-none resize-none" />
                    </div>
                    <div>
                      <label className="block text-sm font-bold text-slate-700 mb-2">Required Skills</label>
                      <textarea rows={4} value={skills} onChange={(e) => setSkills(e.target.value)} placeholder="Awaiting AI generation..." className="w-full px-4 py-3 border rounded-lg outline-none resize-none" />
                    </div>
                  </div>
                )}
              </div>

              {/* NAVIGATION FOOTER */}
              <div className="absolute bottom-0 left-0 right-0 p-4 border-t border-slate-200 bg-white flex justify-between items-center">
                <div className="flex gap-3">
                  <button 
                    onClick={onClose}
                    className="px-6 py-2.5 text-slate-500 font-bold hover:bg-slate-100 rounded-lg transition-colors"
                  >
                    Cancel
                  </button>

                  <button 
                    onClick={() => {
                      setFormError(""); 
                      setActiveStep(prev => Math.max(1, prev - 1));
                    }}
                    disabled={activeStep === 1 || isPublishing}
                    className="px-6 py-2.5 text-slate-700 font-bold border border-slate-200 hover:bg-slate-50 rounded-lg disabled:opacity-30 flex items-center gap-2 transition-colors"
                  >
                    <ArrowLeft size={16} /> Back
                  </button>
                </div>
                
                {activeStep < 3 ? (
                  <button 
                    onClick={handleNextStep}
                    className="px-6 py-2.5 bg-slate-900 hover:bg-slate-800 text-white font-bold rounded-lg flex items-center gap-2 transition-colors"
                  >
                    Next Step <ArrowRight size={16} />
                  </button>
                ) : (
                  <button 
                    onClick={handlePublishJob}
                    disabled={isPublishing}
                    className="px-8 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg shadow-lg flex items-center gap-2 transition-colors disabled:bg-blue-400"
                  >
                    {isPublishing ? (
                      <><Loader2 size={16} className="animate-spin" /> Publishing...</>
                    ) : (
                      <>Publish Job Requisition <CheckCircle2 size={16} /></>
                    )}
                  </button>
                )}
              </div>
              
            </div>

            {/* Right Column: AI Job Architect */}
            <div className="flex-[1] bg-gradient-to-b from-[#f0f4ff] to-[#f8fafc] flex flex-col relative">
              <div className="p-8 flex-1">
                <div className="flex items-center gap-3 mb-8">
                  <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center text-white shadow-md">
                    <Bot size={24} />
                  </div>
                  <div>
                    <h3 className="font-bold text-slate-900 text-lg">AI Job Architect</h3>
                    <span className="text-[10px] font-bold text-blue-600 border border-blue-200 bg-blue-100 px-2 py-0.5 rounded uppercase">Enterprise Brain v4.2</span>
                  </div>
                </div>

                <div className="bg-white border border-blue-200 rounded-xl p-5 shadow-sm text-sm text-slate-700 space-y-4">
                  <p>I see you're drafting a <span className="font-bold text-blue-700">{title || 'New'}</span> role for <span className="font-bold text-blue-700">{department || 'your department'}</span> in <span className="font-bold text-blue-700">{location.split(',')[0] || 'your location'}</span>.</p>
                  <p>I can generate a high-precision job profile based on industry standards.</p>
                </div>
              </div>

              <div className="p-8 bg-white/50 backdrop-blur border-t border-blue-100/50">
                <button 
                  onClick={handleGenerate}
                  disabled={isGenerating || activeStep >= 3}
                  className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-xl shadow-lg disabled:bg-blue-400 flex justify-center items-center gap-2"
                >
                  {isGenerating ? (
                    <><Loader2 size={16} className="animate-spin" /> Generating...</>
                  ) : (
                    <><Sparkles size={16} /> Generate Profile</>
                  )}
                </button>
              </div>
            </div>

          </div>
        )}

      </div>
    </div>
  );
}