import os
import sys
from datetime import datetime # 🚀 IMPORTED FOR TIMESTAMP
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional 
from supabase import create_client, Client

# Initialize the router with the proper prefix matching your frontend API calls
router = APIRouter(prefix="/api/communications", tags=["Communications"])
supabase: Client = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))

# --- DATA TRANSFERS SCHEMAS ---
class SendEmailPayload(BaseModel):
    candidate_id: str
    job_id: Optional[str] = None  # 🚀 FIX: Made optional to prevent 422 errors!
    subject: str
    body: str

# ==========================================================
# 🚀 ENDPOINT 1: FETCH COMMUNICATION THREAD FOR A CANDIDATE
# Handles: GET /api/communications/{candidate_id}?job_id=xyz
# ==========================================================
@router.get("/{candidate_id}")
async def get_candidate_communications(candidate_id: str, job_id: Optional[str] = None):
    """Fetches the complete sorted message history for a single candidate."""
    try:
        print(f"🔍 Fetching communication thread for candidate ID: {candidate_id}, Job ID: {job_id}")
        
        # Base query to get communications for the candidate
        query = supabase.table("communications").select("*").eq("candidate_id", candidate_id)
        
        # If the frontend passes a job_id, filter the emails!
        if job_id:
            query = query.eq("job_id", job_id)
            
        res = query.order("logged_at", desc=False).execute()
            
        return {"communications": res.data or []}

    except Exception as e:
        print(f"❌ Error fetching communications: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch communication logs: {str(e)}")

# ==========================================================
# 🚀 ENDPOINT 2: SEND OUTBOUND EMAIL VIA RECRIUTMENT TOOL
# Handles: POST /api/communications/send
# ==========================================================
@router.post("/send")
async def send_outbound_email(payload: SendEmailPayload):
    """Sends an email message via your Gmail Service and pushes an outbound tracking entry to the DB."""
    try:
        print(f"🚀 Outreach event triggered for candidate: {payload.candidate_id} on job: {payload.job_id}")
        
        # 1. Fetch the candidate's core profile information to get their destination email
        candidate_res = supabase.table("candidates") \
            .select("email, name, company_id") \
            .eq("id", payload.candidate_id) \
            .execute()
            
        if not candidate_res.data:
            raise HTTPException(status_code=404, detail="Candidate target record not found.")
            
        candidate_data = candidate_res.data[0]
        destination_email = candidate_data.get("email")
        company_id = candidate_data.get("company_id")
        
        if not destination_email:
            raise HTTPException(status_code=400, detail="Candidate record does not possess a valid target email address.")

        # 2. ⚡ FIRE GMAIL OUTBOUND ENGINE HERE
        # Dynamically add the root project directory to Python's system path
        current_dir = os.path.dirname(os.path.abspath(__file__))
        parent_dir = os.path.dirname(current_dir)
        
        if parent_dir not in sys.path:
            sys.path.insert(0, parent_dir)
        if current_dir not in sys.path:
            sys.path.insert(0, current_dir)

        # Now import the service cleanly
        try:
            from services.email.gmail_service import MultiTenantGmailService 
            gmail_agent = MultiTenantGmailService(company_id=company_id)
        except ImportError:
            # Fallback just in case the class is named 'GmailService' inside that file
            from services.email.gmail_service import GmailService
            gmail_agent = GmailService(company_id=company_id)

        # Send the actual email AND CAPTURE THE GOOGLE IDS
        send_result = gmail_agent.send_message(
            to=destination_email,
            subject=payload.subject,
            body=payload.body
        )
        
        # 🚀 THE FIX: Extract the IDs generated by Google
        google_message_id = send_result.get('id')
        google_thread_id = send_result.get('threadId')
        
        print(f"✉️ Gmail payload safely dispatched to: {destination_email}. Thread ID: {google_thread_id}")

        # 3. Log the outbound message to the communications ledger table 
        db_insertion = supabase.table("communications").insert({
            "candidate_id": payload.candidate_id,
            "job_id": payload.job_id if payload.job_id else None,  
            "company_id": company_id,
            "type": "outbound_email",
            "sender": "Recruiter",  
            "subject": payload.subject,
            "content": payload.body,
            "received_at": datetime.utcnow().isoformat(), # 🚀 ADDED: Fixes the 'Invalid Date' error in the UI
            "message_id": google_message_id, # 🚀 NOW SAVING TO DB
            "thread_id": google_thread_id    # 🚀 NOW SAVING TO DB
        }).execute()

        return {
            "status": "success", 
            "message": "Outbound communication dispatched and logged successfully",
            "log_entry": db_insertion.data[0] if db_insertion.data else None
        }

    except HTTPException as http_err:
        raise http_err
    except Exception as e:
        print(f"❌ Failed to process outbound transmission: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Internal system email dispatch failure: {str(e)}")